spring.datasource.url=jdbc:mysql://localhost:3306/db_tesi
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spegne il grande logo ASCII iniziale
spring.main.banner-mode=off

# Imposta il livello di log a ERROR (mostra solo se qualcosa esplode davvero)
logging.level.root=ERROR

# Questo zittisce anche i log iniziali della classe Main
logging.level.tesi.Applicazione=ERROR

# Usa il database per salvare i Job
spring.quartz.job-store-type=jdbc

# Crea le tabelle automaticamente al primo avvio
spring.quartz.jdbc.initialize-schema=always

# Aggiorna lo schema se aggiungi colonne, ma non cancella i dati
spring.jpa.hibernate.ddl-auto=update